# Generated by Django 5.2.13 on 2026-05-02 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matric_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('nationality', models.CharField(default='Nigerian', max_length=50)),
                ('state_of_origin', models.CharField(blank=True, max_length=50)),
                ('lga', models.CharField(blank=True, max_length=50)),
                ('admission_status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('admitted', 'Admitted'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='applied', max_length=20)),
                ('current_level', models.IntegerField(default=100)),
                ('clearance_status', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='academic.academicsession')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.programme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
                'ordering': ['matric_number'],
            },
        ),
        migrations.CreateModel(
            name='GraduationClearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cleared_by_library', models.BooleanField(default=False)),
                ('cleared_by_hostel', models.BooleanField(default=False)),
                ('cleared_by_bursary', models.BooleanField(default=False)),
                ('cleared_by_department', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('eligible_to_graduate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clearance', to='student.studentprofile')),
            ],
            options={
                'db_table': 'graduation_clearance',
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='active', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academic.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academic.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academic.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='student.studentprofile')),
            ],
            options={
                'db_table': 'course_registrations',
                'unique_together': {('student', 'course', 'session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(max_length=50)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('qr_verification_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='student.studentprofile')),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jamb_reg_no', models.CharField(blank=True, max_length=20)),
                ('jamb_score', models.IntegerField(blank=True, null=True)),
                ('o_level_result', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('admitted', 'Admitted'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='applied', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='academic.academicsession')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='student.studentprofile')),
            ],
            options={
                'db_table': 'admission_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('qr_verification_code', models.CharField(max_length=50, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='student.studentprofile')),
            ],
            options={
                'db_table': 'transcripts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=2)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved_hod', 'Approved by HOD'), ('approved_dean', 'Approved by Dean'), ('approved_senate', 'Approved by Senate'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('hod_comment', models.TextField(blank=True)),
                ('dean_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_approved_results', to=settings.AUTH_USER_MODEL)),
                ('approved_by_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_results', to=settings.AUTH_USER_MODEL)),
                ('approved_by_senate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senate_approved_results', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_results', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student.courseregistration')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academic.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academic.academicsession')),
            ],
            options={
                'db_table': 'results',
                'unique_together': {('registration', 'session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CGPAHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_gpas', to='academic.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_gpas', to='academic.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cgpa_history', to='student.studentprofile')),
            ],
            options={
                'db_table': 'cgpa_history',
                'unique_together': {('student', 'session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 6=sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='academic.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='academic.semester')),
            ],
            options={
                'db_table': 'timetable_entries',
                'unique_together': {('course', 'day_of_week', 'semester')},
            },
        ),
    ]
