# Generated by Django 5.2.13 on 2026-05-02 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('graduation_year', models.IntegerField()),
                ('degree_awarded', models.CharField(max_length=100)),
                ('class_of_degree', models.CharField(max_length=30)),
                ('is_employed', models.BooleanField(default=False)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('capacity', models.IntegerField()),
                ('occupied', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cv_url', models.URLField(blank=True)),
                ('highest_qualification', models.CharField(max_length=50)),
                ('status', models.CharField(default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('employment_type', models.CharField(default='permanent', max_length=20)),
                ('level', models.CharField(default='lecturer', max_length=50)),
                ('minimum_qualification', models.CharField(default='PhD', max_length=50)),
                ('job_description', models.TextField()),
                ('posting_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('annual_leave_days', models.IntegerField(default=21)),
                ('annual_used', models.IntegerField(default=0)),
                ('sick_leave_days', models.IntegerField(default=14)),
                ('sick_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.UUIDField()),
                ('leave_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('working_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('hod_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=20)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('can_view_fees', models.BooleanField(default=True)),
                ('can_view_results', models.BooleanField(default=True)),
                ('can_make_payments', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('incident_date', models.DateField()),
                ('incident_location', models.CharField(max_length=100)),
                ('incident_description', models.TextField()),
                ('offence_type', models.CharField(max_length=30)),
                ('severity', models.CharField(default='minor', max_length=20)),
                ('action', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='reported', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentHostelAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('hostel_id', models.UUIDField()),
                ('block', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('room_number', models.CharField(max_length=20)),
                ('bed_number', models.IntegerField()),
                ('room_type', models.CharField(default='double', max_length=20)),
                ('hostel_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='allocated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Nigerian', max_length=50)),
                ('state_of_origin', models.CharField(blank=True, max_length=50)),
                ('local_govt_area', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_phone', models.CharField(blank=True, max_length=20)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('genotype', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('secondary_school', models.CharField(blank=True, max_length=200)),
                ('jamb_registration_number', models.CharField(blank=True, max_length=20)),
                ('jamb_score', models.IntegerField(blank=True, null=True)),
                ('o_level_results', models.JSONField(default=dict)),
                ('application_status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
