[pytest]
DJANGO_SETTINGS_MODULE = unicore.settings
python_files = test_*.py *_test.py
python_classes = Test* *Tests
python_functions = test_*
addopts = -v --tb=short
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
