# Generated by Django 5.2.14 on 2026-05-07 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_merge_0002_initial_0002_programmetype"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # FIRST: Add all new fields BEFORE altering unique_together
        migrations.AddField(
            model_name="leavebalance",
            name="year",
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="accrued_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="carried_over_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="promotionrecord",
            name="from_grade",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="promotionrecord",
            name="to_grade",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="alternative_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="confirmation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="grade",
            field=models.CharField(
                blank=True, help_text="GL10, GL12, etc.", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="step",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="termination_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="termination_reason",
            field=models.TextField(blank=True),
        ),
        # SECOND: Alter unique_together AFTER adding fields
        migrations.AlterModelOptions(
            name="leavebalance",
            options={"ordering": ["-year"]},
        ),
        migrations.AlterUniqueTogether(
            name="leaveaccrualconfig",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("staff", "leave_type", "year")},
        ),
        # THIRD: Alter existing fields
        migrations.AlterField(
            model_name="leaveaccrualconfig",
            name="accrual_frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leaveaccrualconfig",
            name="leave_type",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("annual", "Annual Leave"),
                    ("sick", "Sick Leave"),
                    ("casual", "Casual Leave"),
                    ("studies", "Study Leave"),
                    ("maternity", "Maternity Leave"),
                    ("paternity", "Paternity Leave"),
                    ("unpaid", "Unpaid Leave"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("annual", "Annual Leave"),
                    ("sick", "Sick Leave"),
                    ("casual", "Casual Leave"),
                    ("studies", "Study Leave"),
                    ("maternity", "Maternity Leave"),
                    ("paternity", "Paternity Leave"),
                    ("unpaid", "Unpaid Leave"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="contract_type",
            field=models.CharField(default="permanent", max_length=20),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lecturer_iii", "Lecturer III"),
                    ("lecturer_ii", "Lecturer II"),
                    ("lecturer_i", "Lecturer I"),
                    ("senior_lecturer", "Senior Lecturer"),
                    ("reader", "Reader (Associate Professor)"),
                    ("professor", "Professor"),
                    ("chief_lecturer", "Chief Lecturer"),
                    ("principal_lecturer", "Principal Lecturer"),
                    ("senior_lecturer_p", "Senior Lecturer"),
                    ("lecturer_p", "Lecturer"),
                    ("hod", "Head of Department"),
                    ("dean", "Dean"),
                    ("registrar", "Registrar"),
                    ("bursar", "Bursar"),
                    ("vc", "Vice Chancellor"),
                    ("chancellor", "Chancellor"),
                    ("senior_staff", "Senior Staff"),
                    ("junior_staff", "Junior Staff"),
                    ("instructor", "Instructor"),
                    ("adjunct_prof", "Adjunct Professor"),
                    ("assistant_prof", "Assistant Professor"),
                    ("associate_prof", "Associate Professor"),
                    ("full_prof", "Professor"),
                    ("endowed_chair", "Endowed Chair"),
                    ("university_prof", "University Professor"),
                    ("dept_chair", "Department Chair"),
                    ("director", "Director"),
                    ("dean_us", "Dean"),
                    ("provost", "Provost"),
                    ("president", "President"),
                    ("chancellor_us", "Chancellor"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="staff_id",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile_dup",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # FOURTH: Add indexes
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["staff", "status"], name="leave_reque_staff_i_71cf7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date"], name="leave_reque_start_d_e77766_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["staff_id"], name="staff_profi_staff_i_359fb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["department", "is_active"],
                name="staff_profi_departm_a8674d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["faculty", "is_active"], name="staff_profi_faculty_d746b2_idx"
            ),
        ),
        # LAST: Remove old field
        migrations.RemoveField(
            model_name="leavebalance",
            name="session",
        ),
    ]