# Generated by Django 5.2.14 on 2026-05-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('academic', '0002_programmetype'),
    ]

    operations = [
    ]
