# Generated by Django 5.2.13 on 2026-05-02 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=200)),
                ('motto', models.CharField(blank=True, max_length=500)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#1e3a8a', max_length=7)),
                ('secondary_color', models.CharField(default='#059669', max_length=7)),
                ('grading_scale_type', models.CharField(choices=[('british_nigerian', 'British/Nigerian (A=70+, 5.0 scale)'), ('american', 'American (A=90+, 4.0 scale)'), ('custom', 'Custom')], default='british_nigerian', max_length=20)),
                ('grading_boundaries', models.JSONField(default=list, help_text='Grade boundaries e.g. [{"grade": "A", "min": 70, "point": 5.0}]')),
                ('academic_year_start', models.DateField()),
                ('semester_structure', models.JSONField(default=list, help_text='e.g. [{"name": "First Semester", "duration_weeks": 16}]')),
                ('payment_gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=20)),
                ('paystack_secret_key', models.CharField(blank=True, max_length=200)),
                ('paystack_public_key', models.CharField(blank=True, max_length=200)),
                ('flutterwave_secret_key', models.CharField(blank=True, max_length=200)),
                ('flutterwave_public_key', models.CharField(blank=True, max_length=200)),
                ('email_provider', models.CharField(choices=[('smtp', 'SMTP'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun')], default='smtp', max_length=20)),
                ('email_host', models.CharField(blank=True, max_length=200)),
                ('email_port', models.IntegerField(default=587)),
                ('email_username', models.CharField(blank=True, max_length=200)),
                ('email_password', models.CharField(blank=True, max_length=200)),
                ('email_from', models.EmailField(blank=True, max_length=254)),
                ('sms_provider', models.CharField(choices=[('sms', 'SMS'), ('twilio', 'Twilio')], default='sms', max_length=20)),
                ('sms_api_key', models.CharField(blank=True, max_length=200)),
                ('setup_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Settings',
                'db_table': 'settings',
            },
        ),
    ]
